### ISSUE TITLE
Crash on program exit

### ISSUE THREAD

**Issue by rr-** [bubblesub/bubblesub#56]
Because of some qt bullshit, api gets destroyed too early and the app crashes when the program exits.

**Comment by Luni-4** [comment]
Is there any clue that might help us to solve this issue?

**Comment by rr-** [comment]
I thought I had it fixed in 9952cca so I'm sorry to hear that you're getting random stack traces (#71). Unfortunately, I am not, so I can't help you with debugging this issue

**Comment by Luni-4** [comment]
I tried with 95d105b, but it's not fixed, I'm always getting random boundary errors:
`fish: 'bubblesub' terminated by signal SIGSEGV (Address boundary error)`

**Comment by Subarashii-no-Fansub** [comment]
Hello
just by starting/stopping bubblesub I have:

```
$ python -m bubblesub
INFO:quamash:Using Qt Implementation: PyQt5
"/proc/42028/root"
warn main The opengl_cb API is not supported anymore.
warn main Use the similar API in render.h instead.
Segmentation fault (core dumped)
```

on another linux os I didn't reproduce :(
